Homepage, template and navigation
canonical-web-and-design/landscape-brochure.internal pull request #3
Opened 2018-11-07 13:13 UTC by deadlight

## Done
Basic Vanilla configuration, base template and homepage

## QA
 - ./run
 - Visit http://0.0.0.0:8031

2018-11-07 13:13 UTC, webteam-app commented
User webteam-app does not have enough permissions to perform necessary checks. Please review user permissions for this repository.

2018-11-07 15:34 UTC, anasereijo commented
see below some changes. should be quite straightforward (sorry if not!)

![landscape home](https://user-images.githubusercontent.com/36884067/48141300-85131600-e2a2-11e8-997d-e1e7358e3d42.png)

2018-11-08 10:44 UTC, webteam-app commented
Starting demo at: https://landscape-canonical-com-canonical-websites-pr-3.run.demo.haus/

2018-11-08 13:32 UTC, anasereijo commented
@deadlight awesome! thanks 👍

2018-11-08 13:40 UTC, anthonydillon commented
@deadlight what is going on with this branch? Is it in review?

2018-11-08 14:29 UTC, deadlight commented
@anthonydillon it is now

2018-11-08 14:39 UTC, anthonydillon requested changes
Some comments inline

2018-11-08 14:39 UTC, anthonydillon commented on static/sass/_patterns_navigation.scss
> +    background-color: #5E2750;
I would suggest replacing with:
```scss
@mixin vf-navigation-default {
  .p-navigation {
    @include vf-navigation-pattern(
      $background-color: $color-navigation-background,
      $border-color: if(lightness($color-navigation-background) > 50, $color-mid-light, transparent),
      $text-color: #5E2750
    );
  }
}
```

2018-11-08 14:39 UTC, anthonydillon commented on templates/_layout.html
> +</script> -->
Please remove commented out code.

2018-11-08 14:39 UTC, anthonydillon commented on templates/_layout.html
> +              <a href="https://www.ubuntu.com/management/ubuntu-advantage" class="external">Learn more about Ubuntu Advantage</a>
https://www.ubuntu.com/support/plans-and-pricing

2018-11-08 14:39 UTC, anthonydillon commented on templates/_layout.html
> +          <p>If you have any problems accessing your account, please <a href="https://www.ubuntu.com/about/contact-us">contact us</a>.
https://www.ubuntu.com/contact-us

2018-11-08 14:39 UTC, anthonydillon commented on templates/landscape/index.html
> +      <img class="" src="https://assets.ubuntu.com/v1/44ac1c31-web-ui-2.gif" alt="Landscape admin splashscreen">
empty class

2018-11-08 14:57 UTC, anthonydillon commented
QA issue:
- Can you remove the `max-height` and `background-image` from small screens
![screenshot_2018-11-08 landscape](https://user-images.githubusercontent.com/1413534/48206547-91f93d80-e366-11e8-8f9b-d5654b024f09.png)

2018-11-08 15:20 UTC, deadlight commented
@anthonydillon ready for re-review

2018-11-08 15:41 UTC, anthonydillon approved these changes
LGTM :+1:

2018-11-08 15:59 UTC, merged